"""Translation adapter. Identity in phase one.

The important property is what this module refuses to do. It translates
TEMPLATES, never rendered sentences containing numbers.

A finished safety sentence like "waves are 2.2 m" passed through a language
model can come back with the number rounded, reformatted, or converted to
another unit -- and that is a safety number reaching a fisherman after being
regenerated by something that does not know it is a safety number. Storing
claims as templates plus slots means the numbers are copied, never rewritten.
That discipline is enforced in core.schemas.recommendation.Templated; this
module is the other half of it.
"""

from __future__ import annotations

__all__ = ["translate_template", "translate"]


def translate_template(template: str, target: str = "en") -> str:
    """Translate a TEMPLATE, with its {slots} left untouched.

    Identity in phase one. When Tamil is added, the slot placeholders must
    survive the round trip exactly -- a translator that renames {min} to
    {\u0b95\u0bc1\u0bb1\u0bc8\u0ba8\u0bcd\u0ba4} breaks every claim silently.
    """
    if target not in ("en",):
        raise NotImplementedError(
            f"Language {target!r} is not supported yet. Add a templates/{target} "
            "directory and a real adapter; do not translate rendered text."
        )
    return template


def translate(text: str, target: str = "en") -> str:
    """Identity. Present so call sites exist before the adapter does."""
    return translate_template(text, target)
