// GENERATED BY scripts/gen_types.py -- DO NOT EDIT.
//
// Source of truth is core/schemas/. CLAUDE.md: frontend types are
// generated from the Pydantic schemas, never hand-written, because a
// hand-written copy drifts within a week.
//
// Regenerate:  python scripts/gen_types.py

export interface Alternative {
  template: string;
  slots?: Record<string, string | number | boolean | null>;
  id: string;
  cost: AlternativeCost;
  verdict: VerdictValue;
  evidence: string[];
}

export interface AlternativeCost {
  extra_distance_km: number;
  extra_steam_time_h?: number | null;
  note?: string | null;
}

export interface Assumption {
  text: string;
  field?: string | null;
  value?: string | number | null;
  source_turn?: string | null;
  confirmed_by_user?: boolean;
}

export interface Caveat {
  text: string;
  applies_to?: string[];
}

export interface Claim {
  template: string;
  slots?: Record<string, string | number | boolean | null>;
  id: string;
  kind: ClaimKind;
  evidence?: string[];
  /** Rule name for DERIVED claims, e.g. 'rule:sea_state_band'. */
  derived_by?: string | null;
}

export type ClaimKind = "observed" | "derived" | "inferred";

export type Comparison = "lte" | "lt" | "gte" | "gt";

export interface Confidence {
  overall: number;
  by_claim?: Record<string, number>;
  basis: string;
}

export interface Driver {
  /** Stable key, e.g. 'wave_height'. */
  id: string;
  label_template: string;
  slots?: Record<string, string | number | boolean | null>;
  evaluation: ThresholdEvaluation;
  /** The instant `evaluation.observed` describes. */
  at: string;
  trajectory?: Trajectory | null;
  /** tool_call_ids. A driver with no evidence is an opinion. */
  evidence: string[];
}

export interface EvidenceEntry {
  tool_call_id: string;
  tool: string;
  args?: Record<string, unknown>;
  output_digest?: Record<string, unknown>;
  /** Dataset or 'deterministic'. */
  source: string;
  retrieved_at?: string | null;
  /** Forecast issue time, distinct from retrieval. */
  issued_at?: string | null;
  native_resolution_deg?: number | null;
  /** Age of the underlying observation. */
  data_age_days?: number | null;
  /** Cloud-free fraction, satellite only. */
  clear_pass_fraction?: number | null;
  /** Set when a 3-day or 7-day composite was used. */
  composite_window_days?: number | null;
  status?: "ok" | "degraded" | "failed";
  error?: string | null;
}

export interface GeoPoint {
  lat: number;
  lon: number;
}

export interface Hypothesis {
  template: string;
  slots?: Record<string, string | number | boolean | null>;
  id: string;
  /** tool_call_id of the test. Untested hypotheses are dropped. */
  tested_by: string;
  supported: boolean;
  test_statistic?: Range | null;
  /** What the test actually did, in one line. */
  test_description?: string | null;
  evidence: string[];
}

export interface NegativeFinding {
  template: string;
  slots?: Record<string, string | number | boolean | null>;
  id: string;
  /** tool_call_id of the check. */
  checked_by: string;
  /** Who would have issued it -- IMD, INCOIS. */
  authority?: string | null;
  valid_until?: string | null;
}

export interface OperationalGuidance {
  template: string;
  slots?: Record<string, string | number | boolean | null>;
  priority: number;
}

export type QueryType = "pfz_locate" | "safety_assess" | "geofence_check" | "causal_explain" | "conditions_report";

export interface Range {
  min: number;
  max: number;
  unit: Unit;
  qualifier?: string | null;
  /** The operationally significant excursion above `max`: a wind gust, a rogue wave allowance. Kept as a number, not text, because the risk function must b */
  peak?: number | null;
}

export interface ReasoningStep {
  step: string;
  tool: string;
  status: "ok" | "degraded" | "failed" | "skipped";
  ms?: number | null;
  note?: string | null;
  tool_call_id?: string | null;
}

export interface Refusal {
  reason: RefusalReason;
  explanation_template: string;
  slots?: Record<string, string | number | null>;
  /** What was asked for, recorded even though refused. */
  requested?: SpatialReference | null;
  /** What we DO cover, so the refusal is useful rather than a wall. */
  supported_region?: string | null;
}

export type RefusalReason = "out_of_region" | "out_of_scope" | "no_data" | "unsafe_to_answer";

export interface ResolvedPlace {
  name?: string | null;
  lat: number;
  lon: number;
  /** e.g. 'landing_centres'. */
  source: string;
  /** tool_call_id. Required. */
  resolved_by: string;
}

export interface Route {
  /** Shelter-leg polyline, verbatim from optimise_route(). */
  waypoints: GeoPoint[];
  distance_km: number;
  estimated_hours: number;
  /** Shelter name from nearest_landing_centre(). */
  destination_name?: string | null;
  /** tool_call_id of the optimise_route() call. Required. */
  computed_by: string;
}

export interface SpatialContext {
  origin?: ResolvedPlace | null;
  vessel_class?: VesselClass | null;
  /** (west, south, east, north) in EPSG:4326. */
  aoi_bbox?: string[] | null;
  /** Turn id this context came from. Every inherited field must also appear in assumptions[] -- the user sees what was assumed. */
  inherited_from_turn?: string | null;
}

export interface SpatialReference {
  /** Place as the user said it, e.g. 'Nagapattinam'. */
  name?: string | null;
  lat?: number | null;
  lon?: number | null;
  /** tool_call_id of the resolution step. If lat/lon are set and this is None, a coordinate was invented and the verifier must reject. */
  resolved_by?: string | null;
  /** Area of interest around the point. */
  radius_km?: number | null;
}

export interface Templated {
  template: string;
  slots?: Record<string, string | number | boolean | null>;
}

export interface Threshold {
  value: number;
  unit: Unit;
  comparison: Comparison;
  /** Citation pointer, e.g. 'risk_thresholds.yaml#wave_height.frp_9m'. An uncited threshold is not admissible. */
  source: string;
  label?: string | null;
}

export interface ThresholdEvaluation {
  observed: Range;
  threshold: Threshold;
  breaching: boolean;
  /** Signed distance from the worst case to the limit, in the threshold's unit. Positive means headroom, negative means the limit is exceeded and by how mu */
  margin: number;
  /** Margin as a fraction of the threshold value. Lets the risk function compare a wave breach against a wind breach on one scale. None when the threshold  */
  margin_fraction?: number | null;
  /** Not breaching, but inside the caution band near the limit. This is what produces a 'marginal' verdict rather than a flat go, and it is the case the id */
  marginal?: boolean;
}

export interface Trajectory {
  direction: "improving" | "worsening" | "steady";
  /** When the driver first crosses its threshold. None if it never does. */
  breaches_at?: string | null;
  /** The value at `later_at`, for the contrast sentence. */
  later?: Range | null;
  later_at?: string | null;
  /** When most of the change happens. Drives 'the change is quick -- most of the build is between 11:00 and 14:00', which is the sentence that actually cha */
  peak_rate_window?: string[] | null;
}

export type TurnBackBasis = "computed_steam_time" | "flat_margin";

export type Unit = "m" | "km" | "nmi" | "kn" | "m/s" | "h" | "s" | "d" | "degT" | "deg" | "degC" | "mg/m3" | "degC/km" | "fraction" | "count" | "index";

export interface Verdict {
  value: VerdictValue;
  /** Internal risk score. Shown in the evidence drawer, never in the spoken answer -- '0.4875' means nothing to a fisherman. */
  score: number;
  /** Human-facing band label for the drawer. */
  band: string;
  /** tool_call_id of the compute_risk_score() call. Required. */
  computed_by: string;
  /** id of the driver that set this verdict. */
  limiting_driver?: string | null;
}

export type VerdictValue = "go" | "marginal" | "no_go";

export type VesselClass = "kattumaram" | "frp_9m" | "mechanised_trawler";

export interface VisualLayer {
  id: string;
  type: "point" | "polygon" | "line" | "raster" | "timeseries" | "vector_field";
  /** tool_call_id supplying the data. */
  ref: string;
  /** Draws the limit line on a timeseries. */
  threshold?: number | null;
  label?: string | null;
  style_hint?: string | null;
}

export interface Window {
  opens: string;
  turn_back: string;
  ashore_by: string;
  timezone?: string;
  /** tool_call_id of the source timeseries. */
  basis: string;
  /** Driver id that closes the window. */
  limiting_driver?: string | null;
  turn_back_basis: TurnBackBasis;
  /** Distance back to port, for the computed case. */
  steam_distance_km?: number | null;
  /** Cruise speed used in the computation. */
  vessel_speed_kn?: number | null;
  steam_time_h?: number | null;
}

export interface Recommendation {
  schema_version?: string;
  query_type: QueryType;
  turn_id: string;
  session_id?: string | null;
  generated_at?: string | null;
  verdict?: Verdict | null;
  refusal?: Refusal | null;
  headline: Templated;
  claims?: Claim[];
  drivers?: Driver[];
  hypotheses?: Hypothesis[];
  negative_findings?: NegativeFinding[];
  operational_guidance?: OperationalGuidance[];
  alternatives?: Alternative[];
  window?: Window | null;
  route?: Route | null;
  spatial_context?: SpatialContext | null;
  assumptions?: Assumption[];
  confidence?: Confidence | null;
  caveats?: Caveat[];
  evidence?: EvidenceEntry[];
  visual_layers?: VisualLayer[];
  reasoning_trace?: ReasoningStep[];
  degraded?: boolean;
  degradation_notes?: string[];
}

export interface ChatRequest {
  query: string;
  /** Opaque client-chosen id. When supplied, a follow-up inherits the previous turn's place and vessel class -- and every inherited slot is listed in assum */
  session_id?: string | null;
  /** Phase one is English only. */
  language?: string;
  /** Include the full typed object. Set False for a thin client. */
  include_recommendation?: boolean;
}

export interface ChatResponse {
  turn_id: string;
  /** answer | clarification | refusal | error */
  state: string;
  answer: string;
  verdict?: string | null;
  /** Set on a clarification: which slots the answer needs before it can be given. */
  missing_slots?: string[];
  /** Suggested answers for the client to render as choices. */
  options?: string[];
  verified?: boolean | null;
  numbers_checked?: number;
  degraded?: boolean;
  /** Requests one agent made to another during this turn, e.g. the ocean agent asking the geospatial agent to check the boundary at a candidate fishing zon */
  collaboration?: string[];
  collaboration_rounds?: number;
  /** What each domain agent concluded about its own results, in its own words. Empty when no LLM was reachable -- the agents then fall back to their rule-b */
  agent_reasoning?: string[];
  /** 'llm' when the model's prose passed the number guard, else 'template'. */
  narration_source?: string;
  llm_provider?: string;
  used_fallback_plan?: boolean;
  duration_ms?: number;
  notes?: string[];
  recommendation?: Record<string, unknown> | null;
}
