"""Generate frontend/src/types.ts from the Pydantic schemas.

    python scripts/gen_types.py

From CLAUDE.md: *Frontend TypeScript types are generated from the Pydantic
schemas. Do not hand-write them; they will drift.* This is that generator.

It walks ``Recommendation``'s JSON schema plus the chat request/response models
and emits interfaces. Deliberately small -- it handles the constructs this
project's schemas actually use (objects, enums, unions with null, arrays,
``$ref``, ``$defs``) and raises on anything else rather than silently emitting
``any``, because an ``any`` here is exactly the drift the rule exists to stop.

Re-run it after changing anything in ``core/schemas/``. ``tests/test_types.py``
fails if the checked-in file is stale.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

OUT = Path(__file__).resolve().parents[1] / "frontend" / "src" / "types.ts"

_PRIMITIVES = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def _ts_type(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "enum" in node:
        return " | ".join(f'"{v}"' for v in node["enum"])
    if "const" in node:
        return f'"{node["const"]}"'
    if "anyOf" in node or "oneOf" in node:
        parts = [_ts_type(v) for v in node.get("anyOf") or node["oneOf"]]
        # Collapse the Optional[...] pattern into `T | null`, deduplicated.
        seen, ordered = set(), []
        for part in parts:
            if part not in seen:
                seen.add(part)
                ordered.append(part)
        return " | ".join(ordered)
    if "allOf" in node and len(node["allOf"]) == 1:
        return _ts_type(node["allOf"][0])

    kind = node.get("type")
    if kind == "array":
        return f"{_ts_type(node.get('items', {'type': 'string'}))}[]"
    if kind == "object" or kind is None:
        extra = node.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Record<string, {_ts_type(extra)}>"
        # A bare object with no declared shape is genuinely open (slots,
        # args). unknown, not any: the caller must narrow it.
        return "Record<string, unknown>"
    if kind in _PRIMITIVES:
        return _PRIMITIVES[kind]
    raise SystemExit(f"gen_types: unhandled schema node {node!r}")


def _interface(name: str, definition: dict[str, Any]) -> str:
    if "enum" in definition:
        values = " | ".join(f'"{v}"' for v in definition["enum"])
        return f"export type {name} = {values};\n"

    required = set(definition.get("required", []))
    lines = [f"export interface {name} {{"]
    for field, spec in (definition.get("properties") or {}).items():
        optional = "" if field in required else "?"
        description = (spec.get("description") or "").strip().replace("\n", " ")
        if description:
            lines.append(f"  /** {description[:150]} */")
        lines.append(f"  {field}{optional}: {_ts_type(spec)};")
    lines.append("}\n")
    return "\n".join(lines)


def main() -> int:
    from core.schemas.recommendation import Recommendation
    from orchestrator.routes.chat import ChatRequest, ChatResponse

    blocks: list[str] = [
        "// GENERATED BY scripts/gen_types.py -- DO NOT EDIT.",
        "//",
        "// Source of truth is core/schemas/. CLAUDE.md: frontend types are",
        "// generated from the Pydantic schemas, never hand-written, because a",
        "// hand-written copy drifts within a week.",
        "//",
        "// Regenerate:  python scripts/gen_types.py",
        "",
    ]

    emitted: set[str] = set()
    for model in (Recommendation, ChatRequest, ChatResponse):
        schema = model.model_json_schema(ref_template="#/$defs/{model}")
        for name, definition in (schema.get("$defs") or {}).items():
            if name not in emitted:
                emitted.add(name)
                blocks.append(_interface(name, definition))
        root = schema.get("title") or model.__name__
        if root not in emitted:
            emitted.add(root)
            blocks.append(_interface(root, schema))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(blocks), encoding="utf-8")
    print(f"wrote {OUT} ({len(emitted)} types)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
