"""LLM narration over a verified recommendation, with a number guard.

This is the one place an LLM touches the safety answer, so the design is
defensive on purpose:

1.  The LLM sees the **deterministic rendering** of an already-verified object,
    not raw data. It rewrites; it does not reason from evidence.
2.  Its output is checked by :func:`number_guard` -- every number in the prose
    must appear in the deterministic rendering it was given. Round 2.44 to
    2.4, and the narration is discarded.
3.  On any failure -- guard, provider, refusal, timeout -- the answer falls
    back to :func:`language.render`, which is always correct and merely less
    fluent. **The system never loses the ability to answer.**

Why the guard is worth building rather than trusting the prompt: a language
model rounding "2.44 km" to "about 2.5 km" is not a hallucination in any
dramatic sense. It is the most natural thing a fluent writer does. It is also a
safety figure being regenerated by something that does not know it is one.
The prompt says not to; the guard makes sure.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from core import config
from core.schemas.recommendation import Recommendation
from language import render
from orchestrator.llm import client as llm

__all__ = ["Narration", "narrate", "number_guard", "extract_numbers", "set_template_fallback", "template_fallback_enabled"]

PROMPT_PATH = Path(__file__).resolve().parent / "prompts" / "synth.md"

#: Matches decimals and integers, including ranges written with a hyphen, and
#: clock times. "0.3-0.44" yields two numbers; "13:00" yields the token 13:00,
#: not 13 and 00, because a time is a single value a fisherman reads whole.
_NUMBER = re.compile(r"\d{1,2}:\d{2}|\d+(?:\.\d+)?")


@dataclass(frozen=True)
class Narration:
    text: str
    source: str
    """``llm`` when the model's prose passed the guard; ``template`` otherwise."""
    model: str = ""
    fallback_reason: str | None = None


def extract_numbers(text: str) -> list[str]:
    """Every numeric token in a string, as written."""
    return _NUMBER.findall(text)


def number_guard(narration: str, reference: str) -> list[str]:
    """Numbers in ``narration`` that do not appear in ``reference``.

    Comparison is on the literal token. 2.4 is not 2.44, and 2.40 is not 2.4
    either -- if the model reformatted a figure, it changed it, and the
    fisherman sees the reformatted version. Empty list means the narration is
    numerically faithful.
    """
    allowed = set(extract_numbers(reference))
    return sorted({n for n in extract_numbers(narration) if n not in allowed})


def _load_prompt() -> str:
    return PROMPT_PATH.read_text(encoding="utf-8")


# Runtime override set by POST /settings. None means models.yaml wins.
# Same pattern as the tier override in orchestrator/llm/client.py: a process
# restart always returns to the YAML value.
_TEMPLATE_FALLBACK_OVERRIDE: bool | None = None


def template_fallback_enabled() -> bool:
    """Whether a failed narration falls back to the template renderer."""
    if _TEMPLATE_FALLBACK_OVERRIDE is not None:
        return _TEMPLATE_FALLBACK_OVERRIDE
    return bool(config.load_yaml("models.yaml").get("allow_template_fallback", True))


def set_template_fallback(value: bool | None) -> bool:
    """Set or clear the template-fallback override. Returns the effective value."""
    global _TEMPLATE_FALLBACK_OVERRIDE
    _TEMPLATE_FALLBACK_OVERRIDE = value
    return template_fallback_enabled()


def narrate(rec: Recommendation, language: str = "en") -> Narration:
    """Produce the paragraph a fisherman reads. Never fails.

    The deterministic rendering is both the LLM's input and the guard's
    reference, so the model can only ever restate numbers it was shown.
    """
    reference = render(rec, language=language)

    if not template_fallback_enabled():
        raise RuntimeError("allow_template_fallback is off; narrate() requires it.")

    result = llm.complete("narrator", system=_load_prompt(), user=reference)
    if not result.ok:
        return Narration(
            text=reference, source="template", fallback_reason=result.error or "LLM unavailable"
        )

    drift = number_guard(result.text, reference)
    if drift:
        return Narration(
            text=reference,
            source="template",
            model=result.model,
            fallback_reason=f"narration introduced numbers not in the assessment: {drift}",
        )

    if rec.verdict is not None and not _verdict_preserved(result.text, rec):
        return Narration(
            text=reference,
            source="template",
            model=result.model,
            fallback_reason="narration did not state the verdict in its opening sentence",
        )

    return Narration(text=result.text, source="llm", model=result.model)


_VERDICT_MARKERS = {
    "no_go": ("do not go", "don't go", "stay in", "not safe", "unsafe"),
    "marginal": ("marginal", "can go, but", "watch the time", "conditional"),
    "go": ("safe to go", "you can go", "conditions are fine", "safe"),
}


def _verdict_preserved(text: str, rec: Recommendation) -> bool:
    """The first sentence must carry the verdict. Rule 2 of the prompt.

    A narration that leads with "the sea is calm" before mentioning the
    downgrade has reordered the answer in a way that reads as reassurance.
    """
    first = re.split(r"(?<=[.!?])\s", text.strip(), maxsplit=1)[0].lower()
    return any(marker in first for marker in _VERDICT_MARKERS[rec.verdict.value.value])
